export let hostPlatforms: Array<any> = [
  {
    'hid': 'Pj5d7oNJmRLV',
    'name': 'Raspberry Pi 1 Model B (Rev 1.0)',
    'tolerance': 3.3,
    'headers': [
      {
        'name': 'P1',
        'rows': '2',
        'pins' : [
          { 'PIN': 1,  'GRP': '3V3',  'TXT': '3.3 V',   'WPI': '', 'ALT': '' },
          { 'PIN': 2,  'GRP': '5V',   'TXT': '5 V',     'WPI': '', 'ALT': '' },
          { 'PIN': 3,  'GRP': 'GPIO', 'TXT': 'GPIO 0',  'WPI': '', 'ALT': 'I2C0_SDA' },
          { 'PIN': 4,  'GRP': '5V',   'TXT': '5 V',     'WPI': '', 'ALT': '' },
          { 'PIN': 5,  'GRP': 'GPIO', 'TXT': 'GPIO 1',  'WPI': '', 'ALT': 'I2C0_SCL' },
          { 'PIN': 6,  'GRP': 'GND',  'TXT': 'Ground',  'WPI': '', 'ALT': '' },
          { 'PIN': 7,  'GRP': 'GPIO', 'TXT': 'GPIO 4',  'WPI': '', 'ALT': 'GPCLK0' },
          { 'PIN': 8,  'GRP': 'GPIO', 'TXT': 'GPIO 14', 'WPI': '', 'ALT': 'UART0_TXD' },
          { 'PIN': 9,  'GRP': 'GND',  'TXT': 'Ground',  'WPI': '', 'ALT': '' },
          { 'PIN': 10, 'GRP': 'GPIO', 'TXT': 'GPIO 15', 'WPI': '', 'ALT': 'UART0_RXD' },
          { 'PIN': 11, 'GRP': 'GPIO', 'TXT': 'GPIO 17', 'WPI': '', 'ALT': '' },
          { 'PIN': 12, 'GRP': 'GPIO', 'TXT': 'GPIO 18', 'WPI': '', 'ALT': 'PCM_CLK' },
          { 'PIN': 13, 'GRP': 'GPIO', 'TXT': 'GPIO 21', 'WPI': '', 'ALT': '' },
          { 'PIN': 14, 'GRP': 'GND',  'TXT': 'Ground',  'WPI': '', 'ALT': '' },
          { 'PIN': 15, 'GRP': 'GPIO', 'TXT': 'GPIO 22', 'WPI': '', 'ALT': '' },
          { 'PIN': 16, 'GRP': 'GPIO', 'TXT': 'GPIO 23', 'WPI': '', 'ALT': '' },
          { 'PIN': 17, 'GRP': '3V3',  'TXT': '3.3 V',   'WPI': '', 'ALT': '' },
          { 'PIN': 18, 'GRP': 'GPIO', 'TXT': 'GPIO 24', 'WPI': '', 'ALT': '' },
          { 'PIN': 19, 'GRP': 'GPIO', 'TXT': 'GPIO 10', 'WPI': '', 'ALT': 'SPI0_MOSI' },
          { 'PIN': 20, 'GRP': 'GND',  'TXT': 'Ground',  'WPI': '', 'ALT': '' },
          { 'PIN': 21, 'GRP': 'GPIO', 'TXT': 'GPIO 9',  'WPI': '', 'ALT': 'SPI0_MISO' },
          { 'PIN': 22, 'GRP': 'GPIO', 'TXT': 'GPIO 25', 'WPI': '', 'ALT': '' },
          { 'PIN': 23, 'GRP': 'GPIO', 'TXT': 'GPIO 11', 'WPI': '', 'ALT': 'SPI0_SCLK' },
          { 'PIN': 24, 'GRP': 'GPIO', 'TXT': 'GPIO 8',  'WPI': '', 'ALT': 'SPI0_CE0_N' },
          { 'PIN': 25, 'GRP': 'GND',  'TXT': 'Ground',  'WPI': '', 'ALT': '' },
          { 'PIN': 26, 'GRP': 'GPIO', 'TXT': 'GPIO 7',  'WPI': '', 'ALT': 'SPI0_CE1_N' },
        ],
      },
    ],
  },
  {
    'hid': 'Xj5d7oNJmRLV',
    'name': 'Raspberry Pi 1 Model A/B (Rev 2.0)',
    'tolerance': 3.3,
    'headers': [
      {
        'name': 'P1',
        'rows': '2',
        'pins' : [
          { 'PIN': 1,  'GRP': '3V3',  'TXT': '3.3 V',   'WPI': '', 'ALT': '' },
          { 'PIN': 2,  'GRP': '5V',   'TXT': '5 V',     'WPI': '', 'ALT': '' },
          { 'PIN': 3,  'GRP': 'GPIO', 'TXT': 'GPIO 2',  'WPI': '', 'ALT': 'I2C1_SDA' },
          { 'PIN': 4,  'GRP': '5V',   'TXT': '5 V',     'WPI': '', 'ALT': '' },
          { 'PIN': 5,  'GRP': 'GPIO', 'TXT': 'GPIO 3',  'WPI': '', 'ALT': 'I2C1_SCL' },
          { 'PIN': 6,  'GRP': 'GND',  'TXT': 'Ground',  'WPI': '', 'ALT': '' },
          { 'PIN': 7,  'GRP': 'GPIO', 'TXT': 'GPIO 4',  'WPI': '', 'ALT': 'GPCLK0' },
          { 'PIN': 8,  'GRP': 'GPIO', 'TXT': 'GPIO 14', 'WPI': '', 'ALT': 'UART0_TXD' },
          { 'PIN': 9,  'GRP': 'GND',  'TXT': 'Ground',  'WPI': '', 'ALT': '' },
          { 'PIN': 10, 'GRP': 'GPIO', 'TXT': 'GPIO 15', 'WPI': '', 'ALT': 'UART0_RXD' },
          { 'PIN': 11, 'GRP': 'GPIO', 'TXT': 'GPIO 17', 'WPI': '', 'ALT': '' },
          { 'PIN': 12, 'GRP': 'GPIO', 'TXT': 'GPIO 18', 'WPI': '', 'ALT': 'PCM_CLK' },
          { 'PIN': 13, 'GRP': 'GPIO', 'TXT': 'GPIO 27', 'WPI': '', 'ALT': '' },
          { 'PIN': 14, 'GRP': 'GND',  'TXT': 'Ground',  'WPI': '', 'ALT': '' },
          { 'PIN': 15, 'GRP': 'GPIO', 'TXT': 'GPIO 22', 'WPI': '', 'ALT': '' },
          { 'PIN': 16, 'GRP': 'GPIO', 'TXT': 'GPIO 23', 'WPI': '', 'ALT': '' },
          { 'PIN': 17, 'GRP': '3V3',  'TXT': '3.3 V',   'WPI': '', 'ALT': '' },
          { 'PIN': 18, 'GRP': 'GPIO', 'TXT': 'GPIO 24', 'WPI': '', 'ALT': '' },
          { 'PIN': 19, 'GRP': 'GPIO', 'TXT': 'GPIO 10', 'WPI': '', 'ALT': 'SPI0_MOSI' },
          { 'PIN': 20, 'GRP': 'GND',  'TXT': 'Ground',  'WPI': '', 'ALT': '' },
          { 'PIN': 21, 'GRP': 'GPIO', 'TXT': 'GPIO 9',  'WPI': '', 'ALT': 'SPI0_MISO' },
          { 'PIN': 22, 'GRP': 'GPIO', 'TXT': 'GPIO 25', 'WPI': '', 'ALT': '' },
          { 'PIN': 23, 'GRP': 'GPIO', 'TXT': 'GPIO 11', 'WPI': '', 'ALT': 'SPI0_SCLK' },
          { 'PIN': 24, 'GRP': 'GPIO', 'TXT': 'GPIO 8',  'WPI': '', 'ALT': 'SPI0_CE0_N' },
          { 'PIN': 25, 'GRP': 'GND',  'TXT': 'Ground',  'WPI': '', 'ALT': '' },
          { 'PIN': 26, 'GRP': 'GPIO', 'TXT': 'GPIO 7',  'WPI': '', 'ALT': 'SPI0_CE1_N' },
        ],
      },
      {
        'name': 'P5',
        'rows': '2',
        'pins' : [
          { 'PIN': 1, 'GRP': '5V',   'TXT': '5 V',     'WPI': '', 'ALT': '' },
          { 'PIN': 2, 'GRP': '3V3',  'TXT': '3.3 V',   'WPI': '', 'ALT': '' },
          { 'PIN': 3, 'GRP': 'GPIO', 'TXT': 'GPIO 28', 'WPI': '', 'ALT': 'I2C0_SDA' },
          { 'PIN': 4, 'GRP': 'GPIO', 'TXT': 'GPIO 29', 'WPI': '', 'ALT': 'I2C0_SCL' },
          { 'PIN': 5, 'GRP': 'GPIO', 'TXT': 'GPIO 30', 'WPI': '', 'ALT': 'PCM_DIN' },
          { 'PIN': 6, 'GRP': 'GPIO', 'TXT': 'GPIO 31', 'WPI': '', 'ALT': '' },
          { 'PIN': 7, 'GRP': 'GND',  'TXT': 'Ground',  'WPI': '', 'ALT': '' },
          { 'PIN': 8, 'GRP': 'GND',  'TXT': 'Ground',  'WPI': '', 'ALT': '' },
        ],
      },
    ],
  },
  {
    'hid': 'Lj5d7oNJmRLV',
    'name': 'Raspberry Pi 1 Model A+/B+',
    'tolerance': 3.3,
    'headers': [
      {
        'name': 'P1',
        'rows': '2',
        'pins' : [
          { 'PIN': 1,  'GRP': '3V3',  'TXT': '3.3 V',   'WPI': '', 'ALT': '' },
          { 'PIN': 2,  'GRP': '5V',   'TXT': '5 V',     'WPI': '', 'ALT': '' },
          { 'PIN': 3,  'GRP': 'GPIO', 'TXT': 'GPIO 2',  'WPI': '', 'ALT': 'I2C1_SDA' },
          { 'PIN': 4,  'GRP': '5V',   'TXT': '5 V',     'WPI': '', 'ALT': '' },
          { 'PIN': 5,  'GRP': 'GPIO', 'TXT': 'GPIO 3',  'WPI': '', 'ALT': 'I2C1_SCL' },
          { 'PIN': 6,  'GRP': 'GND',  'TXT': 'Ground',  'WPI': '', 'ALT': '' },
          { 'PIN': 7,  'GRP': 'GPIO', 'TXT': 'GPIO 4',  'WPI': '', 'ALT': '' },
          { 'PIN': 8,  'GRP': 'GPIO', 'TXT': 'GPIO 14', 'WPI': '', 'ALT': 'UART0_TXD' },
          { 'PIN': 9,  'GRP': 'GND',  'TXT': 'Ground',  'WPI': '', 'ALT': '' },
          { 'PIN': 10, 'GRP': 'GPIO', 'TXT': 'GPIO 15', 'WPI': '', 'ALT': 'UART0_RXD' },
          { 'PIN': 11, 'GRP': 'GPIO', 'TXT': 'GPIO 17', 'WPI': '', 'ALT': '' },
          { 'PIN': 12, 'GRP': 'GPIO', 'TXT': 'GPIO 18', 'WPI': '', 'ALT': 'PCM_CLK' },
          { 'PIN': 13, 'GRP': 'GPIO', 'TXT': 'GPIO 27', 'WPI': '', 'ALT': '' },
          { 'PIN': 14, 'GRP': 'GND',  'TXT': 'Ground',  'WPI': '', 'ALT': '' },
          { 'PIN': 15, 'GRP': 'GPIO', 'TXT': 'GPIO 22', 'WPI': '', 'ALT': '' },
          { 'PIN': 16, 'GRP': 'GPIO', 'TXT': 'GPIO 23', 'WPI': '', 'ALT': '' },
          { 'PIN': 17, 'GRP': '3V3',  'TXT': '3.3 V',   'WPI': '', 'ALT': '' },
          { 'PIN': 18, 'GRP': 'GPIO', 'TXT': 'GPIO 24', 'WPI': '', 'ALT': '' },
          { 'PIN': 19, 'GRP': 'GPIO', 'TXT': 'GPIO 10', 'WPI': '', 'ALT': 'SPI0_MOSI' },
          { 'PIN': 20, 'GRP': 'GND',  'TXT': 'Ground',  'WPI': '', 'ALT': '' },
          { 'PIN': 21, 'GRP': 'GPIO', 'TXT': 'GPIO 9',  'WPI': '', 'ALT': 'SPI0_MISO' },
          { 'PIN': 22, 'GRP': 'GPIO', 'TXT': 'GPIO 25', 'WPI': '', 'ALT': '' },
          { 'PIN': 23, 'GRP': 'GPIO', 'TXT': 'GPIO 11', 'WPI': '', 'ALT': 'SPI0_SCLK' },
          { 'PIN': 24, 'GRP': 'GPIO', 'TXT': 'GPIO 8',  'WPI': '', 'ALT': 'SPI0_CE0_N' },
          { 'PIN': 25, 'GRP': 'GND',  'TXT': 'Ground',  'WPI': '', 'ALT': '' },
          { 'PIN': 26, 'GRP': 'GPIO', 'TXT': 'GPIO 7',  'WPI': '', 'ALT': 'SPI0_CE1_N' },
          { 'PIN': 27, 'GRP': 'GPIO', 'TXT': 'ID_SD',   'WPI': '', 'ALT': 'I2C ID EEPROM' },
          { 'PIN': 28, 'GRP': 'GPIO', 'TXT': 'ID_SC',   'WPI': '', 'ALT': 'I2C ID EEPROM' },
          { 'PIN': 29, 'GRP': 'GPIO', 'TXT': 'GPIO 5',  'WPI': '', 'ALT': '' },
          { 'PIN': 30, 'GRP': 'GND',  'TXT': 'Ground',  'WPI': '', 'ALT': '' },
          { 'PIN': 31, 'GRP': 'GPIO', 'TXT': 'GPIO 6',  'WPI': '', 'ALT': '' },
          { 'PIN': 32, 'GRP': 'GPIO', 'TXT': 'GPIO 12', 'WPI': '', 'ALT': '' },
          { 'PIN': 33, 'GRP': 'GPIO', 'TXT': 'GPIO 13', 'WPI': '', 'ALT': '' },
          { 'PIN': 34, 'GRP': 'GND',  'TXT': 'Ground',  'WPI': '', 'ALT': '' },
          { 'PIN': 35, 'GRP': 'GPIO', 'TXT': 'GPIO 19', 'WPI': '', 'ALT': '' },
          { 'PIN': 36, 'GRP': 'GPIO', 'TXT': 'GPIO 16', 'WPI': '', 'ALT': '' },
          { 'PIN': 37, 'GRP': 'GPIO', 'TXT': 'GPIO 26', 'WPI': '', 'ALT': '' },
          { 'PIN': 38, 'GRP': 'GPIO', 'TXT': 'GPIO 20', 'WPI': '', 'ALT': '' },
          { 'PIN': 39, 'GRP': 'GND',  'TXT': 'Ground',  'WPI': '', 'ALT': '' },
          { 'PIN': 40, 'GRP': 'GPIO', 'TXT': 'GPIO 21', 'WPI': '', 'ALT': '' },
        ],
      },
    ],
  },
  {
    'hid': 'Tj5d7oNJmRLV',
    'name': 'Raspberry Pi 2/3 Model B',
    'tolerance': 3.3,
    'headers': [
      {
        'name': 'P1',
        'rows': '2',
        'pins' : [
          { 'PIN': 1,  'GRP': '3V3',  'TXT': '3.3 V',   'WPI': '', 'ALT': '' },
          { 'PIN': 2,  'GRP': '5V',   'TXT': '5 V',     'WPI': '', 'ALT': '' },
          { 'PIN': 3,  'GRP': 'GPIO', 'TXT': 'GPIO 2',  'WPI': '', 'ALT': 'I2C1_SDA' },
          { 'PIN': 4,  'GRP': '5V',   'TXT': '5 V',     'WPI': '', 'ALT': '' },
          { 'PIN': 5,  'GRP': 'GPIO', 'TXT': 'GPIO 3',  'WPI': '', 'ALT': 'I2C1_SCL' },
          { 'PIN': 6,  'GRP': 'GND',  'TXT': 'Ground',  'WPI': '', 'ALT': '' },
          { 'PIN': 7,  'GRP': 'GPIO', 'TXT': 'GPIO 4',  'WPI': '', 'ALT': '' },
          { 'PIN': 8,  'GRP': 'GPIO', 'TXT': 'GPIO 14', 'WPI': '', 'ALT': 'UART0_TXD' },
          { 'PIN': 9,  'GRP': 'GND',  'TXT': 'Ground',  'WPI': '', 'ALT': '' },
          { 'PIN': 10, 'GRP': 'GPIO', 'TXT': 'GPIO 15', 'WPI': '', 'ALT': 'UART0_RXD' },
          { 'PIN': 11, 'GRP': 'GPIO', 'TXT': 'GPIO 17', 'WPI': '', 'ALT': '' },
          { 'PIN': 12, 'GRP': 'GPIO', 'TXT': 'GPIO 18', 'WPI': '', 'ALT': 'PCM_CLK' },
          { 'PIN': 13, 'GRP': 'GPIO', 'TXT': 'GPIO 27', 'WPI': '', 'ALT': '' },
          { 'PIN': 14, 'GRP': 'GND',  'TXT': 'Ground',  'WPI': '', 'ALT': '' },
          { 'PIN': 15, 'GRP': 'GPIO', 'TXT': 'GPIO 22', 'WPI': '', 'ALT': '' },
          { 'PIN': 16, 'GRP': 'GPIO', 'TXT': 'GPIO 23', 'WPI': '', 'ALT': '' },
          { 'PIN': 17, 'GRP': '3V3',  'TXT': '3.3 V',   'WPI': '', 'ALT': '' },
          { 'PIN': 18, 'GRP': 'GPIO', 'TXT': 'GPIO 24', 'WPI': '', 'ALT': '' },
          { 'PIN': 19, 'GRP': 'GPIO', 'TXT': 'GPIO 10', 'WPI': '', 'ALT': 'SPI0_MOSI' },
          { 'PIN': 20, 'GRP': 'GND',  'TXT': 'Ground',  'WPI': '', 'ALT': '' },
          { 'PIN': 21, 'GRP': 'GPIO', 'TXT': 'GPIO 9',  'WPI': '', 'ALT': 'SPI0_MISO' },
          { 'PIN': 22, 'GRP': 'GPIO', 'TXT': 'GPIO 25', 'WPI': '', 'ALT': '' },
          { 'PIN': 23, 'GRP': 'GPIO', 'TXT': 'GPIO 11', 'WPI': '', 'ALT': 'SPI0_SCLK' },
          { 'PIN': 24, 'GRP': 'GPIO', 'TXT': 'GPIO 8',  'WPI': '', 'ALT': 'SPI0_CE0_N' },
          { 'PIN': 25, 'GRP': 'GND',  'TXT': 'Ground',  'WPI': '', 'ALT': '' },
          { 'PIN': 26, 'GRP': 'GPIO', 'TXT': 'GPIO 7',  'WPI': '', 'ALT': 'SPI0_CE1_N' },
          { 'PIN': 27, 'GRP': 'GPIO', 'TXT': 'ID_SD',   'WPI': '', 'ALT': 'I2C ID EEPROM' },
          { 'PIN': 28, 'GRP': 'GPIO', 'TXT': 'ID_SC',   'WPI': '', 'ALT': 'I2C ID EEPROM' },
          { 'PIN': 29, 'GRP': 'GPIO', 'TXT': 'GPIO 5',  'WPI': '', 'ALT': '' },
          { 'PIN': 30, 'GRP': 'GND',  'TXT': 'Ground',  'WPI': '', 'ALT': '' },
          { 'PIN': 31, 'GRP': 'GPIO', 'TXT': 'GPIO 6',  'WPI': '', 'ALT': '' },
          { 'PIN': 32, 'GRP': 'GPIO', 'TXT': 'GPIO 12', 'WPI': '', 'ALT': '' },
          { 'PIN': 33, 'GRP': 'GPIO', 'TXT': 'GPIO 13', 'WPI': '', 'ALT': '' },
          { 'PIN': 34, 'GRP': 'GND',  'TXT': 'Ground',  'WPI': '', 'ALT': '' },
          { 'PIN': 35, 'GRP': 'GPIO', 'TXT': 'GPIO 19', 'WPI': '', 'ALT': '' },
          { 'PIN': 36, 'GRP': 'GPIO', 'TXT': 'GPIO 16', 'WPI': '', 'ALT': '' },
          { 'PIN': 37, 'GRP': 'GPIO', 'TXT': 'GPIO 26', 'WPI': '', 'ALT': '' },
          { 'PIN': 38, 'GRP': 'GPIO', 'TXT': 'GPIO 20', 'WPI': '', 'ALT': '' },
          { 'PIN': 39, 'GRP': 'GND',  'TXT': 'Ground',  'WPI': '', 'ALT': '' },
          { 'PIN': 40, 'GRP': 'GPIO', 'TXT': 'GPIO 21', 'WPI': '', 'ALT': '' },
        ],
      },
    ],
  },
  {
    'hid': 'Ks5d7oNJmRLV',
    'name': 'Odroid C1',
    'tolerance': 3.3,
    'headers': [
      {
        'name': 'J2',
        'rows': '2',
        'pins' : [
          { 'PIN': 1,  'GRP': '3V3',  'TXT': '3.3 V',    'WPI': '', 'ALT': '' },
          { 'PIN': 2,  'GRP': '5V',   'TXT': '5 V',      'WPI': '', 'ALT': '' },
          { 'PIN': 3,  'GRP': 'GPIO', 'TXT': 'GPIO 74',  'WPI': '', 'ALT': 'I2CA_SDA' },
          { 'PIN': 4,  'GRP': '5V',   'TXT': '5 V',      'WPI': '', 'ALT': '' },
          { 'PIN': 5,  'GRP': 'GPIO', 'TXT': 'GPIO 75',  'WPI': '', 'ALT': 'I2CA_SCL' },
          { 'PIN': 6,  'GRP': 'GND',  'TXT': 'Ground',   'WPI': '', 'ALT': '' },
          { 'PIN': 7,  'GRP': 'GPIO', 'TXT': 'GPIO 83',  'WPI': 7,  'ALT': '' },
          { 'PIN': 8,  'GRP': 'GPIO', 'TXT': 'GPIO 113', 'WPI': '', 'ALT': 'UART1_TXD' },
          { 'PIN': 9,  'GRP': 'GND',  'TXT': 'Ground',   'WPI': '', 'ALT': '' },
          { 'PIN': 10, 'GRP': 'GPIO', 'TXT': 'GPIO 114', 'WPI': '', 'ALT': 'UART1_RXD' },
          { 'PIN': 11, 'GRP': 'GPIO', 'TXT': 'GPIO 88',  'WPI': 0,  'ALT': '' },
          { 'PIN': 12, 'GRP': 'GPIO', 'TXT': 'GPIO 87',  'WPI': 1,  'ALT': 'PCM_CLK' },
          { 'PIN': 13, 'GRP': 'GPIO', 'TXT': 'GPIO 116', 'WPI': 2,  'ALT': '' },
          { 'PIN': 14, 'GRP': 'GND',  'TXT': 'Ground',   'WPI': '', 'ALT': '' },
          { 'PIN': 15, 'GRP': 'GPIO', 'TXT': 'GPIO 115', 'WPI': 3,  'ALT': '' },
          { 'PIN': 16, 'GRP': 'GPIO', 'TXT': 'GPIO 104', 'WPI': 4,  'ALT': '' },
          { 'PIN': 17, 'GRP': '3V3',  'TXT': '3.3 V',    'WPI': '', 'ALT': '' },
          { 'PIN': 18, 'GRP': 'GPIO', 'TXT': 'GPIO 102', 'WPI': 5,  'ALT': '' },
          { 'PIN': 19, 'GRP': 'GPIO', 'TXT': 'GPIO 107', 'WPI': 12, 'ALT': 'SPI0_MOSI/PWM1' },
          { 'PIN': 20, 'GRP': 'GND',  'TXT': 'Ground',   'WPI': '', 'ALT': '' },
          { 'PIN': 21, 'GRP': 'GPIO', 'TXT': 'GPIO 106', 'WPI': 13, 'ALT': 'SPI0_MISO' },
          { 'PIN': 22, 'GRP': 'GPIO', 'TXT': 'GPIO 103', 'WPI': 6,  'ALT': '' },
          { 'PIN': 23, 'GRP': 'GPIO', 'TXT': 'GPIO 105', 'WPI': 14, 'ALT': 'SPI0_SCLK' },
          { 'PIN': 24, 'GRP': 'GPIO', 'TXT': 'GPIO 117', 'WPI': 10, 'ALT': '' },
          { 'PIN': 25, 'GRP': 'GND',  'TXT': 'Ground',   'WPI': '', 'ALT': '' },
          { 'PIN': 26, 'GRP': 'GPIO', 'TXT': 'GPIO 118', 'WPI': 11, 'ALT': '' },
          { 'PIN': 27, 'GRP': 'GPIO', 'TXT': 'GPIO 76',  'WPI': '', 'ALT': 'I2CB_SDA' },
          { 'PIN': 28, 'GRP': 'GPIO', 'TXT': 'GPIO 77',  'WPI': '', 'ALT': 'I2CB_SCL' },
          { 'PIN': 29, 'GRP': 'GPIO', 'TXT': 'GPIO 101', 'WPI': 21, 'ALT': '' },
          { 'PIN': 30, 'GRP': 'GND',  'TXT': 'Ground',   'WPI': '', 'ALT': '' },
          { 'PIN': 31, 'GRP': 'GPIO', 'TXT': 'GPIO 100', 'WPI': 22, 'ALT': '' },
          { 'PIN': 32, 'GRP': 'GPIO', 'TXT': 'GPIO 99',  'WPI': 26, 'ALT': '' },
          { 'PIN': 33, 'GRP': 'GPIO', 'TXT': 'GPIO 108', 'WPI': 23, 'ALT': 'PWM0' },
          { 'PIN': 34, 'GRP': 'GND',  'TXT': 'Ground',   'WPI': '', 'ALT': '' },
          { 'PIN': 35, 'GRP': 'GPIO', 'TXT': 'GPIO 97',  'WPI': 24, 'ALT': '' },
          { 'PIN': 36, 'GRP': 'GPIO', 'TXT': 'GPIO 98',  'WPI': 27, 'ALT': '' },
          { 'PIN': 37, 'GRP': 'ADC',  'TXT': '10bit ADC #1 (<=1.8V)', 'WPI': '', 'ALT': '' },
          { 'PIN': 38, 'GRP': 'ADR',  'TXT': '1.8V ADC Ref', 'WPI': '', 'ALT': '' },
          { 'PIN': 39, 'GRP': 'GND',  'TXT': 'Ground',   'WPI': '', 'ALT': '' },
          { 'PIN': 40, 'GRP': 'ADC',  'TXT': '10bit ADC #0 (<=1.8V)', 'WPI': '', 'ALT': '' },
        ],
      },
    ],
  },
  {
    'hid': 'OkB4Xa6ZeKpT',
    'name': 'Odroid C2',
    'tolerance': 3.3,
    'headers': [
      {
        'name': 'P1',
        'rows': '2',
        'pins' : [
          // FIXME
        ],
      },
    ],
  },
  {
    'hid': '6UzG7oNJmRLV',
    'name': 'Gl.Inet AR300M',
    'tolerance': 3.3,
    'headers': [
      {
        'name': 'P1',
        'pins' : [
          // FIXME
        ],
      },
    ],
  },
];
