export let hostPlatforms: Array<any> = [
  {
    'hid': 'Pj5d7oNJmRLV',
    'name': 'Raspberry Pi 1 Model B (Rev 1.0)',
    'headers': [{
      'P1': [
        { 'PIN': 1,   'name': '3.3 V',    'BCM': '', 'ALT': '' },
        { 'PIN': 2,   'name': '5 V',      'BCM': '', 'ALT': '' },
        { 'PIN': 3,   'name': 'GPIO 0',   'BCM': '', 'ALT': 'SDA0 I2C' },
        { 'PIN': 4,   'name': '5 V',      'BCM': '', 'ALT': '' },
        { 'PIN': 5,   'name': 'GPIO 1',   'BCM': '', 'ALT': 'SCL0 I2C' },
        { 'PIN': 6,   'name': 'Ground',   'BCM': '', 'ALT': '' },
        { 'PIN': 7,   'name': 'GPIO 4',   'BCM': '', 'ALT': 'GPCLK0' },
        { 'PIN': 8,   'name': 'GPIO 14',  'BCM': '', 'ALT': 'UART0_TXD' },
        { 'PIN': 9,   'name': 'Ground',   'BCM': '', 'ALT': '' },
        { 'PIN': 10,  'name': 'GPIO 15',  'BCM': '', 'ALT': 'UART0_RXD' },
        { 'PIN': 11,  'name': 'GPIO 17',  'BCM': '', 'ALT': '' },
        { 'PIN': 12,  'name': 'GPIO 18',  'BCM': '', 'ALT': 'PCM_CLK' },
        { 'PIN': 13,  'name': 'GPIO 21',  'BCM': '', 'ALT': '' },
        { 'PIN': 14,  'name': 'Ground',   'BCM': '', 'ALT': '' },
        { 'PIN': 15,  'name': 'GPIO 22',  'BCM': '', 'ALT': '' },
        { 'PIN': 16,  'name': 'GPIO 23',  'BCM': '', 'ALT': '' },
        { 'PIN': 17,  'name': '3.3 V',    'BCM': '', 'ALT': '' },
        { 'PIN': 18,  'name': 'GPIO 24',  'BCM': '', 'ALT': '' },
        { 'PIN': 19,  'name': 'GPIO 10',  'BCM': '', 'ALT': 'SPI0_MOSI' },
        { 'PIN': 20,  'name': 'Ground',   'BCM': '', 'ALT': '' },
        { 'PIN': 21,  'name': 'GPIO 9',   'BCM': '', 'ALT': 'SPI0_MISO' },
        { 'PIN': 22,  'name': 'GPIO 25',  'BCM': '', 'ALT': '' },
        { 'PIN': 23,  'name': 'GPIO 11',  'BCM': '', 'ALT': 'SPI0_SCLK' },
        { 'PIN': 24,  'name': 'GPIO 8',   'BCM': '', 'ALT': 'SPI0_CE0_N' },
        { 'PIN': 25,  'name': 'Ground',   'BCM': '', 'ALT': '' },
        { 'PIN': 26,  'name': 'GPIO 7',   'BCM': '', 'ALT': 'SPI0_CE1_N' },
      ],
      'P5': [],
    }],
  },
  {
    'hid': 'Xj5d7oNJmRLV',
    'name': 'Raspberry Pi 1 Model A/B (Rev 2.0)',
    'headers': [{
      'P1': [
        { 'PIN': 1,   'name': '3.3 V',    'BCM': '', 'ALT': '' },
        { 'PIN': 2,   'name': '5 V',      'BCM': '', 'ALT': '' },
        { 'PIN': 3,   'name': 'GPIO 2',   'BCM': '', 'ALT': 'SDA1 I2C' },
        { 'PIN': 4,   'name': '5 V',      'BCM': '', 'ALT': '' },
        { 'PIN': 5,   'name': 'GPIO 3',   'BCM': '', 'ALT': 'SCL1 I2C' },
        { 'PIN': 6,   'name': 'Ground',   'BCM': '', 'ALT': '' },
        { 'PIN': 7,   'name': 'GPIO 4',   'BCM': '', 'ALT': 'GPCLK0' },
        { 'PIN': 8,   'name': 'GPIO 14',  'BCM': '', 'ALT': 'UART0_TXD' },
        { 'PIN': 9,   'name': 'Ground',   'BCM': '', 'ALT': '' },
        { 'PIN': 10,  'name': 'GPIO 15',  'BCM': '', 'ALT': 'UART0_RXD' },
        { 'PIN': 11,  'name': 'GPIO 17',  'BCM': '', 'ALT': '' },
        { 'PIN': 12,  'name': 'GPIO 18',  'BCM': '', 'ALT': 'PCM_CLK' },
        { 'PIN': 13,  'name': 'GPIO 27',  'BCM': '', 'ALT': '' },
        { 'PIN': 14,  'name': 'Ground',   'BCM': '', 'ALT': '' },
        { 'PIN': 15,  'name': 'GPIO 22',  'BCM': '', 'ALT': '' },
        { 'PIN': 16,  'name': 'GPIO 23',  'BCM': '', 'ALT': '' },
        { 'PIN': 17,  'name': '3.3 V',    'BCM': '', 'ALT': '' },
        { 'PIN': 18,  'name': 'GPIO 24',  'BCM': '', 'ALT': '' },
        { 'PIN': 19,  'name': 'GPIO 10',  'BCM': '', 'ALT': 'SPI0_MOSI' },
        { 'PIN': 20,  'name': 'Ground',   'BCM': '', 'ALT': '' },
        { 'PIN': 21,  'name': 'GPIO 9',   'BCM': '', 'ALT': 'SPI0_MISO' },
        { 'PIN': 22,  'name': 'GPIO 25',  'BCM': '', 'ALT': '' },
        { 'PIN': 23,  'name': 'GPIO 11',  'BCM': '', 'ALT': 'SPI0_SCLK' },
        { 'PIN': 24,  'name': 'GPIO 8',   'BCM': '', 'ALT': 'SPI0_CE0_N' },
        { 'PIN': 25,  'name': 'Ground',   'BCM': '', 'ALT': '' },
        { 'PIN': 26,  'name': 'GPIO 7',   'BCM': '', 'ALT': 'SPI0_CE1_N' },
      ],
      'P5': [],
    }],
  },
  {
    'hid': 'Lj5d7oNJmRLV',
    'name': 'Raspberry Pi 1 Model A+/B+',
    'headers': [{
      'P1': [
        { 'PIN': 1,   'name': '3.3 V',    'BCM': '', 'ALT': '' },
        { 'PIN': 2,   'name': '5 V',      'BCM': '', 'ALT': '' },
        { 'PIN': 3,   'name': 'GPIO 2',   'BCM': '', 'ALT': 'SDA1 I2C' },
        { 'PIN': 4,   'name': '5 V',      'BCM': '', 'ALT': '' },
        { 'PIN': 5,   'name': 'GPIO 3',   'BCM': '', 'ALT': 'SCL1 I2C' },
        { 'PIN': 6,   'name': 'Ground',   'BCM': '', 'ALT': '' },
        { 'PIN': 7,   'name': 'GPIO 4',   'BCM': '', 'ALT': '' },
        { 'PIN': 8,   'name': 'GPIO 14',  'BCM': '', 'ALT': 'UART0_TXD' },
        { 'PIN': 9,   'name': 'Ground',   'BCM': '', 'ALT': '' },
        { 'PIN': 10,  'name': 'GPIO 15',  'BCM': '', 'ALT': 'UART0_RXD' },
        { 'PIN': 11,  'name': 'GPIO 17',  'BCM': '', 'ALT': '' },
        { 'PIN': 12,  'name': 'GPIO 18',  'BCM': '', 'ALT': 'PCM_CLK' },
        { 'PIN': 13,  'name': 'GPIO 27',  'BCM': '', 'ALT': '' },
        { 'PIN': 14,  'name': 'Ground',   'BCM': '', 'ALT': '' },
        { 'PIN': 15,  'name': 'GPIO 22',  'BCM': '', 'ALT': '' },
        { 'PIN': 16,  'name': 'GPIO 23',  'BCM': '', 'ALT': '' },
        { 'PIN': 17,  'name': '3.3 V',    'BCM': '', 'ALT': '' },
        { 'PIN': 18,  'name': 'GPIO 24',  'BCM': '', 'ALT': '' },
        { 'PIN': 19,  'name': 'GPIO 10',  'BCM': '', 'ALT': 'SPI0_MOSI' },
        { 'PIN': 20,  'name': 'Ground',   'BCM': '', 'ALT': '' },
        { 'PIN': 21,  'name': 'GPIO 9',   'BCM': '', 'ALT': 'SPI0_MISO' },
        { 'PIN': 22,  'name': 'GPIO 25',  'BCM': '', 'ALT': '' },
        { 'PIN': 23,  'name': 'GPIO 11',  'BCM': '', 'ALT': 'SPI0_SCLK' },
        { 'PIN': 24,  'name': 'GPIO 8',   'BCM': '', 'ALT': 'SPI0_CE0_N' },
        { 'PIN': 25,  'name': 'Ground',   'BCM': '', 'ALT': '' },
        { 'PIN': 26,  'name': 'GPIO 7',   'BCM': '', 'ALT': 'SPI0_CE1_N' },
        { 'PIN': 27,  'name': 'ID_SD',    'BCM': '', 'ALT': 'I2C ID EEPROM' },
        { 'PIN': 28,  'name': 'ID_SC',    'BCM': '', 'ALT': 'I2C ID EEPROM' },
        { 'PIN': 29,  'name': 'GPIO 5',   'BCM': '', 'ALT': '' },
        { 'PIN': 30,  'name': 'Ground',   'BCM': '', 'ALT': '' },
        { 'PIN': 31,  'name': 'GPIO 6',   'BCM': '', 'ALT': '' },
        { 'PIN': 32,  'name': 'GPIO 12',  'BCM': '', 'ALT': '' },
        { 'PIN': 33,  'name': 'GPIO 13',  'BCM': '', 'ALT': '' },
        { 'PIN': 34,  'name': 'Ground',   'BCM': '', 'ALT': '' },
        { 'PIN': 35,  'name': 'GPIO 19',  'BCM': '', 'ALT': '' },
        { 'PIN': 36,  'name': 'GPIO 16',  'BCM': '', 'ALT': '' },
        { 'PIN': 37,  'name': 'GPIO 26',  'BCM': '', 'ALT': '' },
        { 'PIN': 38,  'name': 'GPIO 20',  'BCM': '', 'ALT': '' },
        { 'PIN': 39,  'name': 'Ground',   'BCM': '', 'ALT': '' },
        { 'PIN': 40,  'name': 'GPIO 21',  'BCM': '', 'ALT': '' },
      ],
      'P5': [],
    }],
  },
  {
    'hid': 'Tj5d7oNJmRLV',
    'name': 'Raspberry Pi 2/3 Model B',
    'headers': [{
      'P1': [
        { 'PIN': 1,   'name': '3.3 V',    'BCM': '', 'ALT': '' },
        { 'PIN': 2,   'name': '5 V',      'BCM': '', 'ALT': '' },
        { 'PIN': 3,   'name': 'GPIO 2',   'BCM': '', 'ALT': 'SDA1 I2C' },
        { 'PIN': 4,   'name': '5 V',      'BCM': '', 'ALT': '' },
        { 'PIN': 5,   'name': 'GPIO 3',   'BCM': '', 'ALT': 'SCL1 I2C' },
        { 'PIN': 6,   'name': 'Ground',   'BCM': '', 'ALT': '' },
        { 'PIN': 7,   'name': 'GPIO 4',   'BCM': '', 'ALT': '' },
        { 'PIN': 8,   'name': 'GPIO 14',  'BCM': '', 'ALT': 'UART0_TXD' },
        { 'PIN': 9,   'name': 'Ground',   'BCM': '', 'ALT': '' },
        { 'PIN': 10,  'name': 'GPIO 15',  'BCM': '', 'ALT': 'UART0_RXD' },
        { 'PIN': 11,  'name': 'GPIO 17',  'BCM': '', 'ALT': '' },
        { 'PIN': 12,  'name': 'GPIO 18',  'BCM': '', 'ALT': 'PCM_CLK' },
        { 'PIN': 13,  'name': 'GPIO 27',  'BCM': '', 'ALT': '' },
        { 'PIN': 14,  'name': 'Ground',   'BCM': '', 'ALT': '' },
        { 'PIN': 15,  'name': 'GPIO 22',  'BCM': '', 'ALT': '' },
        { 'PIN': 16,  'name': 'GPIO 23',  'BCM': '', 'ALT': '' },
        { 'PIN': 17,  'name': '3.3 V',    'BCM': '', 'ALT': '' },
        { 'PIN': 18,  'name': 'GPIO 24',  'BCM': '', 'ALT': '' },
        { 'PIN': 19,  'name': 'GPIO 10',  'BCM': '', 'ALT': 'SPI0_MOSI' },
        { 'PIN': 20,  'name': 'Ground',   'BCM': '', 'ALT': '' },
        { 'PIN': 21,  'name': 'GPIO 9',   'BCM': '', 'ALT': 'SPI0_MISO' },
        { 'PIN': 22,  'name': 'GPIO 25',  'BCM': '', 'ALT': '' },
        { 'PIN': 23,  'name': 'GPIO 11',  'BCM': '', 'ALT': 'SPI0_SCLK' },
        { 'PIN': 24,  'name': 'GPIO 8',   'BCM': '', 'ALT': 'SPI0_CE0_N' },
        { 'PIN': 25,  'name': 'Ground',   'BCM': '', 'ALT': '' },
        { 'PIN': 26,  'name': 'GPIO 7',   'BCM': '', 'ALT': 'SPI0_CE1_N' },
        { 'PIN': 27,  'name': 'ID_SD',    'BCM': '', 'ALT': 'I2C ID EEPROM' },
        { 'PIN': 28,  'name': 'ID_SC',    'BCM': '', 'ALT': 'I2C ID EEPROM' },
        { 'PIN': 29,  'name': 'GPIO 5',   'BCM': '', 'ALT': '' },
        { 'PIN': 30,  'name': 'Ground',   'BCM': '', 'ALT': '' },
        { 'PIN': 31,  'name': 'GPIO 6',   'BCM': '', 'ALT': '' },
        { 'PIN': 32,  'name': 'GPIO 12',  'BCM': '', 'ALT': '' },
        { 'PIN': 33,  'name': 'GPIO 13',  'BCM': '', 'ALT': '' },
        { 'PIN': 34,  'name': 'Ground',   'BCM': '', 'ALT': '' },
        { 'PIN': 35,  'name': 'GPIO 19',  'BCM': '', 'ALT': '' },
        { 'PIN': 36,  'name': 'GPIO 16',  'BCM': '', 'ALT': '' },
        { 'PIN': 37,  'name': 'GPIO 26',  'BCM': '', 'ALT': '' },
        { 'PIN': 38,  'name': 'GPIO 20',  'BCM': '', 'ALT': '' },
        { 'PIN': 39,  'name': 'Ground',   'BCM': '', 'ALT': '' },
        { 'PIN': 40,  'name': 'GPIO 21',  'BCM': '', 'ALT': '' },
      ],
      'P5': [],
    }],
  },
  {
    'hid': 'Ks5d7oNJmRLV',
    'name': 'Odroid C1',
    'headers': [{
      'P1': [

      ],
    }],
  },
  {
    'hid': 'Ks5d7oNJmRLV',
    'name': 'Odroid C2',
    'headers': [{
      'P1': [

      ],
    }],
  },
  {
    'hid': '6UzG7oNJmRLV',
    'name': 'Gl.Inet AR300M',
    'headers': [{
      'P1': [

      ],
    }],
  },
];
