export const taskMock: Array<any> = [{
    'tid': 'pGJz1rZwp8EG',
    'aid': 'K4aMt1gLsT2e',
    'name': 'Reflow Lead-Free',
    'icon': 'star-outline',
    'ctime': Math.round( new Date().getTime() / 1000 ),
    'mtime': '',
    'notes': '',
    'type': 'profile',
    'constraints': true,
    'data': [
      {
        'control': 'Temperature',
        'type': 'number',
        'icon': 'thermometer',
        'active': true,
        'show': true,
        'options': {
          'yAxisID': 'y-axis-1',
          'color': 'rgba(255, 152, 0, 1)',
          'fill': false,
          'drawPoints': true,
          'pointRadius': 3,
          'pointBorderWidth': 2,
          'strokeWidth': 2,
        },
        'points': [
          [0, 25],
          [82, 151],
          [162, 185],
          [197, 225],
          [202, 225],
          [233, 175],
          [300, 50],
        ],
      },
      {
        'control': 'Circulation',
        'type': 'boolean',
        'icon': 'nuclear',
        'active': true,
        'show': true,
        'options': {
          'yAxisID': 'y-axis-2',
          'color': 'rgba(144, 73, 249, 1)',
          'fill': true,
          'drawPoints': true,
          'pointRadius': 0,
          'pointBorderWidth': 1,
          'strokeWidth': 1,
        },
        'points': [
          [0, 1],
          [175, 1],
          [176, 0],
          [233, 0],
          [234, 1],
          [300, 1],
        ],
      },
    ],
  },
];
