export const pluginMock: any = {
  'input': [
    {
      'pid': 'Dj7r8741OdrV',
      'driver': 'Simple GPIO Input Driver',
      'name': 'Simple GPIO Input Driver',
      'desc': 'A simple, polled GPIO PIN state reader implementation',
      'group': 'GPIO',
      'color': 'rgba(167, 68, 208, 0.75)',
      'icon': 'star',
      'conf': [
        { 'name': 'INVERTED', 'type': 'boolean', 'value': false },
        { 'name': 'SAMPLE-BIN-SIZE', 'type': 'int', 'unit': 's', 'value': 1, 'min': 1, 'max': 16 },
        { 'name': 'SAMPLE-INTERVAL', 'type': 'int', 'unit': 's', 'value': 1, 'min': 0.1, 'max': '' },
        { 'name': 'STORE-INTERVAL', 'type': 'int', 'unit': 's', 'value': 1, 'min': 0, 'max': '' },
        { 'name': 'DB-ICON-SHOW', 'type': 'boolean', 'value': true },
      ],
      'input': [
        { 'name': 'PIN', 'type': 'hostGPIO', 'value': '' },
      ],
      'output': [
        { 'name': 'STATE', 'type': 'boolean' },
      ],
    },
    {
      'pid': 'kj2glRJoKen3',
      'driver': 'Hallsensor RPM Input Driver',
      'name': 'Hallsensor RPM Input Driver',
      'desc': '',
      'group': 'GPIO',
      'color': 'rgba(69, 184, 135, 0.75)',
      'icon': 'cog',
      'conf': [
        { 'name': 'INVERTED', 'type': 'boolean', 'value': false },
        { 'name': 'SAMPLE-BIN-SIZE', 'type': 'int', 'unit': 's', 'value': 1, 'min': 1, 'max': 16 },
        { 'name': 'SAMPLE-INTERVAL', 'type': 'int', 'unit': 's', 'value': 1, 'min': 0.1, 'max': '' },
        { 'name': 'STORE-INTERVAL', 'type': 'int', 'unit': 's', 'value': 1, 'min': 0, 'max': '' },
        { 'name': 'DB-DISPLAY-SHOW', 'type': 'boolean', 'value': true },
      ],
      'input': [
        { 'name': 'PIN', 'type': 'hostGPIO', 'value': '' },
      ],
      'output': [
        { 'name': 'RPM', 'type': 'float' },
      ],
    },
    {
      'pid': 'Gk2plRto8enT',
      'driver': 'DS18B20+ Input Driver',
      'name': 'DS18B20+ Input Driver',
      'desc': '',
      'group': '1WIRE',
      'color': 'rgba(191, 128, 6, 0.75)',
      'icon': 'thermometer',
      'conf': [
        { 'name': 'UNIT', 'value': '°C' },
        { 'name': 'SAMPLE-BIN-SIZE', 'type': 'int', 'unit': 's', 'value': 1, 'min': 1, 'max': 16 },
        { 'name': 'SAMPLE-INTERVAL', 'type': 'int', 'unit': 's', 'value': 1, 'min': 0.1, 'max': '' },
        { 'name': 'STORE-INTERVAL', 'type': 'int', 'unit': 's', 'value': 1, 'min': 0, 'max': '' },
        { 'name': 'DB-DISPLAY-SHOW', 'type': 'boolean', 'value': true },
      ],
      'input': [
        { 'name': 'PIN', 'type': 'hostGPIO', 'value': '' },
      ],
      'output': [
        { 'name': 'TEMP', 'type': 'float', 'unit': '°C' },
      ],
    },
    {
      'pid': '6jy2rwNevEy3',
      'driver': 'MAX31885 K-Type Thermocouple Adapter Driver',
      'name': 'MAX31885 K-Type Thermocouple Adapter Driver',
      'desc': '',
      'group': 'SPI',
      'unit': '°C',
      'color': 'rgba(191, 128, 6, 0.75)',
      'icon': 'thermometer',
      'conf': [
        { 'name': 'UNIT', 'value': '°C' },
        { 'name': 'SAMPLE-BIN-SIZE', 'type': 'int', 'unit': 's', 'value': 1, 'min': 1, 'max': 16 },
        { 'name': 'SAMPLE-INTERVAL', 'type': 'int', 'unit': 's', 'value': 1, 'min': 0.1, 'max': '' },
        { 'name': 'STORE-INTERVAL', 'type': 'int', 'unit': 's', 'value': 1, 'min': 0, 'max': '' },
        { 'name': 'DB-DISPLAY-SHOW', 'type': 'boolean', 'value': true },
      ],
      'input': [
        { 'name': 'CSEL', 'type': 'hostGPIO', 'value': '' },
        { 'name': 'CLCK', 'type': 'hostGPIO', 'value': '' },
        { 'name': 'DATA', 'type': 'hostGPIO', 'value': '' },
      ],
      'output': [
        { 'name': 'TEMP', 'type': 'float', 'unit': '°C' },
      ],
    },
    {
      'pid': 'e3Evoz7A8leG',
      'driver': 'MAX6675 K-Type Thermocouple Adapter Driver',
      'name': 'MAX6675 K-Type Thermocouple Adapter Driver',
      'desc': '',
      'group': 'SPI',
      'color': 'rgba(191, 128, 6, 0.75)',
      'icon': 'thermometer',
      'conf': [
        { 'name': 'UNIT', 'value': '°C' },
        { 'name': 'SAMPLE-BIN-SIZE', 'type': 'int', 'unit': 's', 'value': 1, 'min': 1, 'max': 16 },
        { 'name': 'SAMPLE-INTERVAL', 'type': 'int', 'unit': 's', 'value': 1, 'min': 0.1, 'max': '' },
        { 'name': 'STORE-INTERVAL', 'type': 'int', 'unit': 's', 'value': 1, 'min': 0, 'max': '' },
        { 'name': 'DB-DISPLAY-SHOW', 'type': 'boolean', 'value': true },
      ],
      'input': [
        { 'name': 'CSEL', 'type': 'hostGPIO', 'value': '' },
        { 'name': 'CLCK', 'type': 'hostGPIO', 'value': '' },
        { 'name': 'DATA', 'type': 'hostGPIO', 'value': '' },
      ],
      'output': [
        { 'name': 'TEMP', 'type': 'float', 'unit': '°C' },
      ],
    },
    {
      'pid': 'qGa6o1nPDQ2V',
      'driver': 'ADS1118 K-Type Thermocouple Adapter Driver',
      'name': 'ADS1118 K-Type Thermocouple Adapter Driver',
      'desc': '16-Bit Analog-to-Digital Converter with Internal Reference and Temperature Sensor',
      'group': 'SPI',
      'color': 'rgba(191, 128, 6, 0.75)',
      'icon': 'thermometer',
      'conf': [
        { 'name': 'UNIT', 'value': '°C' },
        { 'name': 'SAMPLE-BIN-SIZE', 'type': 'int', 'unit': 's', 'value': 1, 'min': 1, 'max': 16 },
        { 'name': 'SAMPLE-INTERVAL', 'type': 'int', 'unit': 's', 'value': 1, 'min': 0.1, 'max': '' },
        { 'name': 'STORE-INTERVAL', 'type': 'int', 'unit': 's', 'value': 1, 'min': 0, 'max': '' },
        { 'name': 'DB-DISPLAY-SHOW', 'type': 'boolean', 'value': true },
      ],
      'input': [
        { 'name': 'SCLK', 'type': 'hostGPIO', 'value': '' },
        { 'name': 'SDO', 'type': 'hostGPIO', 'value': '' },
        { 'name': 'SDI', 'type': 'hostGPIO', 'value': '' },
        { 'name': '/SS', 'type': 'hostGPIO', 'value': '' },
      ],
      'output': [
        { 'name': 'TEMP', 'type': 'float', 'unit': '°C' },
      ],
    },
    {
      'pid': 'Tfh8LP2iXxA3',
      'driver': 'HX711 Load Cell Amplifier Driver',
      'name': 'HX711 Load Cell Amplifier Driver',
      'desc': 'Measures weight by reading the changes in load cell resistance. Handy for creating scales, process controls, thrust/force analyzer or simple presence detection',
      'group': 'I2C',
      'color': 'rgba(66, 198, 95, 0.75)',
      'icon': 'arrow-round-down',
      'conf': [
        { 'name': 'DB-DISPLAY-SHOW', 'type': 'boolean', 'value': true },
        { 'name': 'UNIT', 'type': 'select', 'value': 'g', 'options': ['mg', 'g', 'Kg'] },
        { 'name': 'SAMPLE-BIN-SIZE', 'type': 'int', 'value': 1, 'min': 1, 'max': 16 },
        { 'name': 'SAMPLE-INTERVAL', 'type': 'float', 'unit': 's', 'value': 1, 'min': 0.1, 'max': '' },
        { 'name': 'STORE-INTERVAL', 'type': 'float', 'unit': 's', 'value': 1, 'min': 1, 'max': '' },
      ],
      'input': [
        { 'name': 'SDA', 'type': 'hostGPIO', 'value': '' },
        { 'name': 'SCL', 'type': 'hostGPIO', 'value': '' },
      ],
      'output': [
        { 'name': 'WEIGHT', 'type': 'float' },
      ],
    },
  ],
  'control': [
    {
      'pid': '2V1PkgReWYWG',
      'driver': 'PID Temperature Governor',
      'name': 'PID Temperature Governor',
      'desc': 'Takes an input from a temperature sensor and has an output that is connected to a control element (heater)',
      'group': 'Temperature',
      'color': 'rgba(209, 110, 46, 0.75)',
      'icon': 'thermometer',
      'conf': [
        { 'name': 'Kp', 'type': 'float', 'value': 0.5, 'min': 0, 'max': 10 },
        { 'name': 'Ki', 'type': 'float', 'value': 0.1, 'min': 0, 'max': 10 },
        { 'name': 'Kd', 'type': 'float', 'value': 0.4, 'min': 0, 'max': 10 },
        { 'name': 'MAN-CTRL-AV', 'type': 'boolean', 'value': true },
      ],
      'input': [
        { 'name': 'TEMP', 'type': 'float', 'value': '' },
      ],
      'output': [
        { 'name': 'HEAT', 'type': 'boolean', 'value': '' },
        { 'name': 'COOL', 'type': 'boolean', 'value': '' },
      ],
      'ctrl': [
        { 'name': 'TEMP', 'type': 'float', 'value': '' },
      ],
    },
    {
      'pid': 'bjQK7erEBoaG',
      'driver': 'PID Speed Governor (PWM)',
      'name': 'PID Speed Governor (PWM)',
      'desc': '',
      'group': 'Speed',
      'color': 'rgba(69, 171, 162, 0.75)',
      'icon': 'cog',
      'conf': [
        { 'name': 'Kp', 'type': 'float', 'value': 1, 'min': 0, 'max': 10 },
        { 'name': 'Ki', 'type': 'float', 'value': 1, 'min': 0, 'max': 10 },
        { 'name': 'Kd', 'type': 'float', 'value': 1, 'min': 0, 'max': 10 },
        { 'name': 'MAN-CTRL-AV', 'type': 'boolean', 'value': true },
      ],
      'input': [
        { 'name': 'RPM', 'type': 'float', 'value': '' },
      ],
      'output': [
        { 'name': 'DT', 'type': 'float', 'value': '', 'min': 0, 'max': 1 },
      ],
      'ctrl': [
        { 'name': 'RPM', 'type': 'float', 'value': '', 'min': 0, 'max': '' },
      ],
    },
  ],
  'output': [
    {
      'pid': '6G6ENp8qrRb3',
      'name': 'Simple GPIO Output Driver',
      'desc': '',
      'group': 'GPIO',
      'type': 'boolean',
      'color': 'rgba(191, 128, 6, 0.75)',
      'icon': 'flame',
      'conf': [
        { 'name': 'INVERTED', 'type': 'boolean', 'value': false },
        { 'name': 'DB-ICON-SHOW', 'type': 'boolean', 'value': true },
        { 'name': 'MAN-CTRL-AV', 'type': 'boolean', 'value': true },
      ],
      'input': [
        { 'name': 'STATE', 'type': 'boolean' },
      ],
      'output': [
        { 'name': 'PIN', 'type': 'hostGPIO', 'value': '' },
      ],
    },
    {
      'pid': 'dGq2woQWDwwV',
      'driver': 'Simple PWM Output Driver',
      'name': 'Simple PWM Output Driver',
      'desc': '',
      'group': 'GPIO',
      'type': 'float',
      'color': 'rgba(65, 114, 186, 0.75)',
      'icon': 'pulse',
      'conf': [
        { 'name': 'INVERTED', 'type': 'boolean', 'value': false },
        { 'name': 'F_SW', 'type': 'int', 'value': 1, 'min': 1, 'max': 1000 },
        { 'name': 'MAN-CTRL-AV', 'type': 'boolean', 'value': true },
      ],
      'input': [
        { 'name': 'DT', 'type': 'float', 'min': 0, 'max': 1 },
      ],
      'output': [
        { 'name': 'PIN', 'type': 'hostGPIO', 'value': '' },
      ],
    },
    {
      'pid': 'pG0gKAPvmvZ3',
      'driver': 'PCA9685 16-Channel 12-Bit PWM Servo Driver',
      'name': 'PCA9685 16-Channel 12-Bit PWM Servo Driver',
      'desc': 'The PCA9685 can control 16 free-running 12-bit PWM outputs for servos',
      'group': 'I2C',
      'type': 'float',
      'color': 'rgba(160, 189, 90, 0.75)',
      'icon': 'pulse',
      'conf': [
        { 'name': 'CHAN', 'type': 'int', 'value': 1, 'min': 1, 'max': 16 },
        { 'name': 'F_SW', 'type': 'int', 'value': 1, 'min': 1, 'max': 1000 },
        { 'name': 'MAN-CTRL-AV', 'type': 'boolean', 'value': true },
      ],
      'input': [
        { 'name': 'DT', 'type': 'float', 'min': 0, 'max': 1 },
      ],
      'output': [
        { 'name': 'SDA', 'type': 'hostGPIO', 'value': '' },
        { 'name': 'SCL', 'type': 'hostGPIO', 'value': '' },
      ],
    },
    {
      'pid': '4gRqDX1akMN0',
      'driver': 'TLC5947 24-Channel 12-Bit PWM LED Driver',
      'name': 'TLC5947 24-Channel 12-Bit PWM LED Driver',
      'desc': 'The TLC5947 can control 24 separate channels of 12-bit PWM output. Designed (and ideal) for LED control',
      'group': 'SPI',
      'type': 'float',
      'color': 'rgba(75, 191, 128, 0.75)',
      'icon': 'pulse',
      'conf': [
        { 'name': 'CHAN', 'type': 'int', 'value': 1, 'min': 1, 'max': 24 },
        { 'name': 'F_SW', 'type': 'int', 'value': 1, 'min': 1, 'max': 1000 },
        { 'name': 'MAN-CTRL-AV', 'type': 'boolean', 'value': true },
      ],
      'input': [
        { 'name': 'DT', 'type': 'float', 'min': 0, 'max': 1 },
      ],
      'output': [
        { 'name': 'DIN', 'type': 'hostGPIO', 'value': 19 },
        { 'name': 'CLK', 'type': 'hostGPIO', 'value': 23 },
        { 'name': 'LAT', 'type': 'hostGPIO', 'value': 24 },
      ],
    },
    {
      'pid': 'bVD0eno5RWkV',
      'driver': 'TLC59711 12-Channel 16-Bit PWM LED Driver',
      'name': 'TLC59711 12-Channel 16-Bit PWM LED Driver',
      'desc': 'The TLC59711 can control 12 separate channels of 16-bit PWM output, ideal for lighting purposes',
      'group': 'SPI',
      'type': 'float',
      'color': 'rgba(114, 92, 199, 0.75)',
      'icon': 'bulb',
      'conf': [
        { 'name': 'CHAN', 'type': 'int', 'value': 1, 'min': 1, 'max': 24 },
        { 'name': 'F_SW', 'type': 'int', 'value': 1, 'min': 1, 'max': 1000 },
        { 'name': 'MAN-CTRL-AV', 'type': 'boolean', 'value': true },
      ],
      'input': [
        { 'name': 'DT', 'type': 'float', 'min': 0, 'max': 1 },
      ],
      'output': [
        { 'name': 'DIN', 'type': 'hostGPIO', 'value': '' },
        { 'name': 'CLK', 'type': 'hostGPIO', 'value': '' },
        { 'name': 'LAT', 'type': 'hostGPIO', 'value': '' },
      ],
    },
  ],
};
