export const pluginMock: any = {
  'input': [
    {
      'pid': 'Dj7r8741OdrV',
      'name': 'Simple GPIO Input Driver',
      'desc': '',
      'group': 'GPIO',
      'type': 'boolean',
      'conf': [
        { 'name': 'PIN' },
        { 'name': 'INV' },
      ],
    },
    {
      'pid': 'kj2glRJoKen3',
      'name': 'Hallsensor RPM Input Driver',
      'desc': '',
      'group': 'GPIO',
      'type': 'float',
      'conf': [
        { 'name': 'PIN' },
        { 'name': 'INV' },
      ],
    },
    {
      'pid': 'Gk2plRto8enT',
      'name': 'DS18B20+ Input Driver',
      'desc': '',
      'group': '1WIRE',
      'type': 'float',
      'conf': [
        { 'name': 'PIN' },
        { 'name': 'INV' },
      ],
    },
    {
      'pid': '6jy2rwNevEy3',
      'name': 'MAX31885 K-Type Thermocouple Adapter Driver',
      'desc': '',
      'group': 'SPI',
      'unit': '°C',
      'type': 'float',
      'conf': [
        { 'name': 'CSEL' },
        { 'name': 'CLCK' },
        { 'name': 'DATA' },
      ],
    },
    {
      'pid': 'e3Evoz7A8leG',
      'name': 'MAX6675 K-Type Thermocouple Adapter Driver',
      'desc': '',
      'group': 'SPI',
      'type': 'float',
      'conf': [
        { 'name': 'CSEL' },
        { 'name': 'CLCK' },
        { 'name': 'DATA' },
      ],
    },
    {
      'pid': 'qGa6o1nPDQ2V',
      'name': 'ADS1118 K-Type Thermocouple Adapter Driver',
      'desc': '16-Bit Analog-to-Digital Converter with Internal Reference and Temperature Sensor',
      'group': 'SPI',
      'type': 'float',
      'conf': [
        { 'name': 'SCLK' },
        { 'name': 'SDO' },
        { 'name': 'SDI' },
        { 'name': '/SS' },
      ],
    },
    {
      'pid': 'Tfh8LP2iXxA3',
      'name': 'HX711 Load Cell Amplifier Driver',
      'desc': 'Measures weight by reading the changes in load cell resistance. Handy for creating scales, process controls, thrust/force analyzer or simple presence detection',
      'group': 'I2C',
      'type': 'float',
      'conf': [
        { 'name': 'SDA' },
        { 'name': 'SCL' },
      ],
    },
  ],
  'control': [
    {
      'pid': '2V1PkgReWYWG',
      'name': 'PID Temperature Governor',
      'desc': '',
      'group': 'Temperature',
      'conf': [
        { 'name': 'TEMP' },
        { 'name': 'HEAT' },
        { 'name': 'COOL' },
        { 'name': 'K_P' },
        { 'name': 'K_I' },
        { 'name': 'K_D' },
      ],
    },
    {
      'pid': 'bjQK7erEBoaG',
      'name': 'PID Speed Governor',
      'desc': '',
      'group': 'Speed',
      'conf': [
        { 'name': 'RPM' },
        { 'name': 'K_P' },
        { 'name': 'K_I' },
        { 'name': 'K_D' },
      ],
    },
  ],
  'output': [
    {
      'pid': '6G6ENp8qrRb3',
      'name': 'Simple GPIO Output Driver',
      'desc': '',
      'group': 'GPIO',
      'type': 'boolean',
      'conf': [
        { 'name': 'PIN' },
        { 'name': 'INV' },
      ],
    },
    {
      'pid': 'dGq2woQWDwwV',
      'name': 'Simple PWM Output Driver',
      'desc': '',
      'group': 'GPIO',
      'type': 'float',
      'conf': [
        { 'name': 'PIN' },
        { 'name': 'INV' },
      ],
    },
    {
      'pid': 'pG0gKAPvmvZ3',
      'name': 'PCA9685 16-Channel 12-Bit PWM Servo Driver',
      'desc': 'To control pwm/servos',
      'group': 'I2C',
      'type': 'float',
      'conf': [
        { 'name': 'CHN' },
        { 'name': 'FSW' },
        { 'name': 'SDA' },
        { 'name': 'SCL' },
      ],
    },
    {
      'pid': '4gRqDX1akMN0',
      'name': 'TLC5947 24-Channel 12-Bit PWM Driver',
      'desc': '',
      'group': 'SPI',
      'type': 'float',
      'conf': [
        { 'name': 'CHN' },
        { 'name': 'FSW' },
        { 'name': 'DIN' },
        { 'name': 'CLK' },
        { 'name': 'LAT' },
      ],
    },
    {
      'pid': 'bVD0eno5RWkV',
      'name': 'TLC59711 12-Channel 16-Bit PWM LED Driver',
      'desc': '',
      'group': 'SPI',
      'type': 'float',
      'conf': [
        { 'name': 'CHN' },
        { 'name': 'FSW' },
        { 'name': 'DIN' },
        { 'name': 'CLK' },
        { 'name': 'LAT' },
      ],
    },
  ],
};
